from django.conf.urls import url

from xui.kumo_integration_kit.apis.spendings import (
    charts_data_rh_json,
    spend_details_for_rh_json,
    filtration_menu_rh_json,
    forecast_for_rh_json,
    cost_adviser_overview_for_rh,
    aws_ri_recommendations_for_rh_json,
    azure_ri_recommendations_for_rh_json,
    get_resource_name,
    get_tag_values,
)
from xui.kumo_integration_kit.apis.efficiency import (
    cost_efficiency_for_rh,
    service_details_for_rh_json,
    csv_download_for_rh_json,
    region_list_for_rh_json,
    ignored_services_list_for_rh_json,
    get_graph_data,
)
from xui.kumo_integration_kit.apis.admin import (
    validate_creds,
    save_creds,
    get_creds,
    get_rh_list,
    save_kumo_data,
    validate_api_token,
    get_config,
    set_config,
    change_recurring_job_status,
    all_currency_conversion,
    save_preferred_currency,
    set_currency_unified_status,
    change_rh_currency_rj_status,
)
from xui.kumo_integration_kit.apis.server import (
    get_cost_summary,
    get_cost_breakdown,
    get_operational_cost,
    get_potential_savings,
)
from xui.kumo_integration_kit.apis.compliance import (
    get_security_trends,
    get_compliance_report,
    get_compliance_overview,
)
from xui.kumo_integration_kit.apis.admin import (
    save_documentation_link
)
from xui.kumo_integration_kit.apis.dashboard_widget import (
    get_compliance_data,
    get_spend_data
)


xui_urlpatterns = [
    url(r"^xui/kumo/api/spend_details_for_rh_json/$",
        spend_details_for_rh_json, name="spend_details_for_rh_json"),
    url(r"^xui/kumo/api/charts_data_rh_json/$",
        charts_data_rh_json, name="charts_data_rh_json"),
    url(r"^xui/kumo/api/filtration_menu_rh_json/$",
        filtration_menu_rh_json, name="filtration_menu_rh_json"),
    url(r"^xui/kumo/api/forecast_for_rh_json/$",
        forecast_for_rh_json, name="forecast_for_rh_json"),
    url(r"^xui/kumo/api/cost_efficiency_for_rh/$",
        cost_efficiency_for_rh, name="cost_efficiency_for_rh"),
    url(r"^xui/kumo/api/service_details_for_rh_json/$",
        service_details_for_rh_json, name="service_details_for_rh_json"),
    url(r"^xui/kumo/api/csv_download_for_rh_json/$",
        csv_download_for_rh_json, name="csv_download_for_rh_json"),
    url(r"^xui/kumo/api/region_list_for_rh_json/$",
        region_list_for_rh_json, name="region_list_for_rh_json"),
    url(r"^xui/kumo/api/ignored_services_list_for_rh_json/$",
        ignored_services_list_for_rh_json, name="ignored_services_list_for_rh_json"),
    url(r"^xui/kumo/api/cost_adviser_overview_for_rh/$",
        cost_adviser_overview_for_rh, name="cost_adviser_overview_for_rh"),
    url(r"^xui/kumo/api/aws_ri_recommendations_for_rh_json/$",
        aws_ri_recommendations_for_rh_json, name="aws_ri_recommendations_for_rh_json"),
    url(r"^xui/kumo/api/azure_ri_recommendations_for_rh_json/$",
        azure_ri_recommendations_for_rh_json, name="azure_ri_recommendations_for_rh_json"),
    url(r"^xui/kumo/api/get_resource_name/$",
        get_resource_name, name="get_resource_name"),
    url(r"^xui/kumo/api/get_tag_values/$",
        get_tag_values, name="get_tag_values"),
    url(r"^xui/kumo/api/get_graph_data/$",
        get_graph_data, name="get_graph_data"),
    url(r"^xui/kumo/api/validate_credentials/$",
        validate_creds, name="validate_creds"),
    url(r"^xui/kumo/api/save_credentials/$",
        save_creds, name="save_creds"),
    url(r"^xui/kumo/api/get_credentials/$",
        get_creds, name="get_creds"),
    url(r"^xui/kumo/api/get_rh_list/$",
        get_rh_list, name="get_rh_list"),
    url(r"^xui/kumo/api/save_kumo_data/$",
        save_kumo_data, name="save_kumo_data"),
    url(r"^xui/kumo/api/validate_api_token/$",
        validate_api_token, name="validate_api_token"),
    url(r"^xui/kumo/api/get_cost_summary/$",
        get_cost_summary, name="get_cost_summary"),
    url(r"^xui/kumo/api/get_cost_breakdown/$",
        get_cost_breakdown, name="get_cost_breakdown"),
    url(r"^xui/kumo/api/get_operational_cost_breakdown/$",
        get_operational_cost, name="get_operational_cost"),
    url(r"^xui/kumo/api/get_potential_savings/$",
        get_potential_savings, name="get_potential_savings"),
    url(r"^xui/kumo/api/get_config/$",
        get_config, name="get_config"),
    url(r"^xui/kumo/api/set_config/$",
        set_config, name="set_config"),
    url(r"^xui/kumo/api/get_security_trends/$",
        get_security_trends, name="get_security_trends"),
    url(r"^xui/kumo/api/get_compliance_report/$",
        get_compliance_report, name="get_compliance_report"),
    url(r"^xui/kumo/api/get_compliance_overview/$",
        get_compliance_overview, name="get_compliance_overview"),
    url(r"^xui/kumo/api/change_rj_status/$",
        change_recurring_job_status, name="change_recurring_job_status"),
    url(r"^xui/kumo/api/change_rh_currency_rj_status/$",
        change_rh_currency_rj_status, name="change_rh_currency_rj_status"),
    url(r"^xui/get_compliance_data/$",
        get_compliance_data, name="get_compliance_data"),
    url(r"^xui/get_spend_data/$",
        get_spend_data, name="get_spend_data"),
    url(r"^xui/kumo/api/all_currency_conv/$",
        all_currency_conversion, name="all_currency_conversion"),
    url(r"^xui/kumo/api/save_preferred_currency/$",
        save_preferred_currency, name="save_preferred_currency"),
    url(r"^xui/kumo/api/set_currency_unified_status/$",
        set_currency_unified_status, name="set_currency_unified_status"),
    url(r"^xui/kumo/api/save_documentation_link/$",
        save_documentation_link, name="save_documentation_link"),
]
