name: Display Changed Files 
on:
  pull_request:
    branches:
      - main

jobs:
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  # Event `pull_request`: Compare the last commit of the main branch or last remote commit of the PR branch -> to the current commit of a PR branch.
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest  
    name: Test changed-files
    strategy:
      matrix:
        type:
          - blueprints
          - ui-extension-packages
          - cb-applets
          - orchestration-actions
          - recurring-jobs
          - server-actions
          - resource-actions
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      
          
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: List folders in S3 bucket
        id: list-folders
        run: |
          folders=$(aws s3api list-objects-v2 --bucket abbybucketcloudformation-dont-delete --delimiter "/" --query "CommonPrefixes[].Prefix" --output text)
          echo "::set-output name=folders::${folders}"

      - name: Download and Update and Upload JSON objects
        run: |
          echo "Folders ${{ steps.list-folders.outputs.folders }}"
          IFS=$'\t' read -ra array <<< "${{ steps.list-folders.outputs.folders }}"
          for element in "${array[@]}"; do
            echo "Processing element: $element"
          done

            
