name: Workflow for User Input Content Item Deployment

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      content_type:
        description: "Type of Content"
        required: true
        type: choice
        options:
          - blueprints
          - ui-extension-packages
          - cb-applets
          - orchestration-actions
          - recurring-jobs
          - server-actions
          - resource-actions

      blueprint_name:
        description: "Name of Content"
        required: true

      version:
        description: "Version for Deployment"
        required: true
        type: choice
        options:
          - 2023.5.21
          - 2023.5.1
          - 2023.4.9
          - 2023.4.8

defaults:
  run:
    shell: bash -leo pipefail {0}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  testing-user-input-workflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # generate a random workflow identifier for CB python script to use
      - name: Printing Inputes provided by User
        run: |
        echo "Blueprint Name : ${{ inputs.content_type }}"
        echo "Blueprint Name : ${{ inputs.blueprint_name }}"
        echo "Blueprint Name : ${{ inputs.version }}"
        